# For Ruby

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_examples_for']
